#!/bin/sh
export X_CSI_UNITY_ENDPOINT=https://0.0.0.0
export X_CSI_UNITY_USER=
export X_CSI_UNITY_PASSWORD=
export X_CSI_UNITY_INSECURE=true
export X_CSI_UNITY_NODENAME=
export X_CSI_PRIVATE_MOUNT_DIR=
export X_CSI_STAGING_TARGET_PATH=
export X_CSI_PUBLISH_TARGET_PATH=
export CSI_ENDPOINT=
export X_CSI_DEBUG=
export STORAGE_POOL=
export STORAGE_POOL_NAME=
export X_CSI_REQ_LOGGING="true"
export X_CSI_REP_LOGGING="true"
export GOUNITY_DEBUG="true"

