#!/bin/sh
export X_CSI_UNITY_NODENAME=
export X_CSI_UNITY_LONGNODENAME=
export X_CSI_STAGING_TARGET_PATH=
export X_CSI_EPHEMERAL_STAGING_PATH=
export X_CSI_PUBLISH_TARGET_PATH=
export CSI_ENDPOINT=
export X_CSI_DEBUG=
export STORAGE_POOL=
export NAS_SERVER=
export X_CSI_REQ_LOGGING="true"
export X_CSI_REP_LOGGING="true"
export GOUNITY_DEBUG="true"
export DRIVER_NAME=
export DRIVER_CONFIG=
export X_CSI_UNITY_AUTOPROBE=
export X_CSI_UNITY_ALLOW_MULTI_POD_ACCESS="true"
export X_CSI_HEALTH_MONITOR_ENABLED="true"