{{ $global := . }}
{{- range $i, $v := .Values.storageArrayList }}
{{- if eq $global.Values.kubeversion "v1.16" }}
apiVersion: snapshot.storage.k8s.io/v1alpha1
{{- else }}
apiVersion: snapshot.storage.k8s.io/v1beta1
{{- end }}
kind: VolumeSnapshotClass
metadata:
  {{- if $v.isDefaultArray }}
  name: "unity-snapclass"
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: {{ $v.isDefaultArray | quote }}
  {{ else }}
  name: {{ "unity" }}-{{ $v.name | lower }}-snapclass
  {{- end }}
{{- if eq $global.Values.kubeversion "v1.16" }}
snapshotter: csi-unity.dellemc.com
{{- else }}
driver: csi-unity.dellemc.com
deletionPolicy: Delete
{{- end }}
parameters:
  retentionDuration: {{ $v.snapshotClass.retentionDuration | default "" | quote  }}
---
{{- end }}

