# This is a sample manifest for utilizing the topology feature and mount options.
# PVCs created using this storage class will be scheduled
# only on the nodes with FC connectivity to the array

# Change all instances of <ARRAY_ID> to the array serial ID of the unisphere instance used

# Provide mount options through "mountOptions" attribute
# to create PVCs with mount options.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: unity-<ARRAY_ID>-fc
# If using custom driver name, change the following to point to the custom name
# Default value: csi-unity.dellemc.com
# Optional: false
# Examples: "csi-driver-unity", "csi-unity.dellemc.com"
provisioner: csi-unity.dellemc.com
# reclaimPolicy - Configure what happens to a Persistent Volume when the PVC
# it is bound to is to be deleted
# Allowed values:
#   Delete: the underlying persistent volume will be deleted along with the persistent volume claim.
#   Retain: the underlying persistent volume remain.
# Optional: false
# Default value: None
reclaimPolicy: Delete
# allowVolumeExpansion - Attribute to allow volume expansion
# Allowed values:
    #   "true"  - Volume can be resized
    #   "false" - Volume cannot be resized
# Optional: true
# Default value: "true"
allowVolumeExpansion: true
# volumeBindingMode- controls when volume binding and dynamic provisioning should occur.
# Allowed values:
#   Immediate- indicates that volume binding and dynamic provisioning
#              occurs once the PersistentVolumeClaim is created
#   WaitForFirstConsumer- will delay the binding and provisioning of a PersistentVolume
#              until a Pod using the PersistentVolumeClaim is created
## Optional: true
# Default value: "Immediate"
volumeBindingMode: WaitForFirstConsumer
parameters:
  # protocol - Defines"FC" or "FIBRE" for fibrechannel, "ISCSI" for iSCSI, or "" for autoselection.
  # Allowed values:
  #   "FC"    - Fiber Channel protocol
  #   "FIBER" - Fiber Channel protocol
  #   "ISCSI" - iSCSI protocol
  #   ""      - Automatic selection of transport protocol
  # Optional: false
  # Default value: ""
  protocol: FC
  # arrayId - Serial Id of the array that will be used for provisioning.
  # Allowed values: String
  # Default value: None
  # Optional: false
  # Examples: "APM000000001", "APM000000002"
  arrayId: <ARRAY_ID>
  #storagePool - Defines storage pool. The value should be picked from the column labeled "CLI ID" of Pools in the Unisphere GUI.
  # Allowed values: String
  # Default value: None
  # Optional: false
  # Examples: pool_0
  storagePool: <STORAGE_POOL>
  #thinProvisioned- Defines Boolean to choose value of thinProvisioned while creating a new volume
  # Allowed values:
  #    "true"      - for thin provision
  #    "false"     - for thick provision
  # Optional: true
  # Default value: false
  thinProvisioned: "true"
  #isDataReductionEnabled - Defines Boolean to choose value of is DataReductionEnabled while creating a new volume
  # Allowed values:
  #    "true"      - Enables data reduction for all-flash storage pool.
  #    "false"     - Disables data reduction.
  # Optional: true
  # Default value: false
  isDataReductionEnabled: "true"
  #TieringPolicy - Tiering policy to be used during provisioning
  #                Requires FAST VP license.
  # Allowed values: String
  # Optional: true
  # Examples: "0"
  # Default value: None
  # Accepted values:
  #   "0" for "Start High Then Auto-Tier"
  #   "1" for "Auto-Tier"
  #   "2" for "Highest Available Tier"
  #   "3" for "Lowest Available Tier"
  tieringPolicy: <TIERING_POLICY>
  # hostIOLimitName - Insert Host IO Limit Name that is to be used for provisioning here.
  # Allowed values: String
  # Optional: true
  # Default value: None
  # Examples: "Autotier"
  hostIOLimitName: <HOST_IO_LIMIT_NAME>
  # csi.storage.k8s.io/fstype - Set the filesystem type to format the new volume
  # Default value: ext4
  # Accepted values:
  #   "ext4"
  #   "xfs"
  csi.storage.k8s.io/fstype: xfs
# Restrict provisioning to specific topologies
# Allowed values: map of key-value pairs
# Optional: false
# Default value: None
# Examples: "apm0020280XXXX" , "apm0021340XXXX"
# Here first three characters  should be in small letters.
allowedTopologies:
  - matchLabelExpressions:
      - key: csi-unity.dellemc.com/<array_id>-fc
        values:
          - "true"
# mountOptions - Defines mount input values.
# Default value: []
# Optional: false
# Examples:
#   "hard"    - option for mounting with NFS
#   "context" - option for mounting with block storage
mountOptions: ["<mountOption1>", "<mountOption2>", ..., "<mountOptionN>"]
